# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-25 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='resever',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='reseiver',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phonenum',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='zip_code',
            field=models.CharField(default='', max_length=6),
        ),
    ]
